FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY MicroserviceApp.sln .
COPY OrderService/ OrderService/
COPY InventoryService/ InventoryService/
COPY Shared/ Shared/

RUN dotnet restore InventoryService/InventoryService.csproj
RUN dotnet publish InventoryService/InventoryService.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "InventoryService.dll"]
